## 파이썬 기본 문법 정리 4

### 1. 객체지향 프로그래밍

#### 객체
- 변수들, 함수들로 구성. 메모리에 올라가 있는 상태

#### 클래스
- 변수들과 함수들이 어떻게 구성된느지의 설계도, 도면, 틀
- 변수 정의, 함수 정의
- 클래스를 정의한 후 객체로 만들어야 사용 가능
- 클래스의 정의 → 새로운 사용자 정의 타입을 만드는 것

#### 클래스 정의 및 객체 생성

In [1]:
class Cookie:
    pass

c1 = Cookie()

print(id(c1), type(c1))

2354142936576 <class '__main__.Cookie'>


In [2]:
# 객체 새로 생성 시 새로운 주소 지정
c1 = Cookie()
c2 = Cookie()

print(id(c1), type(c1))
print(id(c2), type(c2))

2354142603024 <class '__main__.Cookie'>
2354142602704 <class '__main__.Cookie'>


In [3]:
#사칙 연산을 하는 클래스 정의
# 변수 2개, 함수(메서드) 4개

class FourCal:
    # 클래스에서 함수를 정의할 때에는 반드시 self 매개변수를 받아야 함
    # self : 객체 자신을 가리키는 변수(객체의 주소) → 호출 시 생략
    def setData(self, first, second):
        self.first = first
        self.second = second

cal_1 = FourCal()
print(type(cal_1))

<class '__main__.FourCal'>


In [4]:
cal_1.setData(10, 20)
print(cal_1.first, cal_1.second)

10 20


In [5]:
cal_2 = FourCal()
print(cal_2.first)

AttributeError: 'FourCal' object has no attribute 'first'

#### 생성자
- 생성자(초기화 메서드) : 변수 선언 후 최초 데이터를 할당
- 필요한 변수들의 생성, 값을 초기화해야 함

In [6]:
# 초기화 메서드 추가
class FourCal:
    # 초기화 메서드
    def __init__(self, first, second):
        self.first = first
        self.second = second

    def setData(self, first, second):
        self.first = first
        self.second = second

cal_3 = FourCal()

TypeError: FourCal.__init__() missing 2 required positional arguments: 'first' and 'second'

#### 객체 생성 실행 흐름
1. FourCal 객체 생성
2. FourCal() 호출 → `__init__()` 호출 → 정의된 매개변수 반드시 정의

In [7]:
cal_3 = FourCal(100, 200)
print(cal_3.first, cal_3.second)

100 200


In [8]:
# 사칙 연산 함수 추가

class FourCal:
    # 초기화 메서드
    def __init__(self, first, second):
        self.first = first
        self.second = second

    def setData(self, first, second):
        self.first = first
        self.second = second
    
    # 사칙 연산 함수
    def add(self):
        return self.first + self.second
    
    def sub(self):
        return self.first - self.second
    
    def mul(self):
        return self.first * self.second
    
    def div(self):
        return self.first / self.second

In [9]:
cal_5 = FourCal(10, 7)
print(f"add: {cal_5.add()}, sub: {cal_5.sub()}, mul: {cal_5.mul()}, div: {cal_5.div()}")

add: 17, sub: 3, mul: 70, div: 1.4285714285714286


#### 연습 문제

In [10]:
# 학생 클래스 생성 후 객체 생성
# 변수: 학번, 이름, 국어점수, 영어점수, 수학점수
# 기능: 전체 데이터(이름, 학번, 총점, 평균) 출력 메서드, 총점 계산 메서드, 평균 계산 메서드
# 시뮬레이션: 테스트 학생 데이터 생성 후 결과 출력

class Student:
    student_sum = 0
    student_avg = 0

    def __init__(self, student_id, student_name, student_kor, student_eng, student_math):
        self.student_id = student_id
        self.student_name = student_name
        self.student_kor = student_kor
        self.student_eng = student_eng
        self.student_math = student_math
    
    def setSum(self):
        self.student_sum = self.student_kor + self.student_eng + self.student_math

    def setAvg(self):
        self.student_avg = (self.student_kor + self.student_eng + self.student_math) / 3
    
    def print_result(self):
        print(f"name: {self.student_name}, id: {self.student_id}, sum: {self.student_sum}, avg: {self.student_avg}")

In [11]:
s1 = Student(22, "하이", 80, 90, 70)
s1.setSum()
s1.setAvg()
s1.print_result()

name: 하이, id: 22, sum: 240, avg: 80.0


##### 모범 답안

In [12]:
class Student:
    
    # 데이터 초기화
    def __init__(self, name, sno, k_score, e_score, m_score):
        self.s_name = name
        self.s_no = sno
        self.k_score = k_score
        self.e_score = e_score
        self.m_score = m_score

    def sum(self):
        return self.k_score + self.e_score + self.m_score
    
    def avg(self):
        return self.sum()/3

    def print_result(self):
        print('성적표', '-'*20)
        print(f'이름: {self.s_name} ({self.s_no})')
        print('국어 :', self.k_score)
        print('영어 :', self.e_score)
        print('수학 :', self.m_score)
        print('총점 :', self.sum())
        print('평균 :', self.avg())

In [13]:
students = [
    Student("하이1", 22, 80, 90, 70),
    Student("하이2", 23, 80, 90, 70),
    Student("하이3", 24, 80, 90, 70),
    Student("하이4", 25, 80, 90, 70),
    Student("하이5", 26, 80, 90, 70),
]

In [14]:
for s in students:
    s.print_result()

성적표 --------------------
이름: 하이1 (22)
국어 : 80
영어 : 90
수학 : 70
총점 : 240
평균 : 80.0
성적표 --------------------
이름: 하이2 (23)
국어 : 80
영어 : 90
수학 : 70
총점 : 240
평균 : 80.0
성적표 --------------------
이름: 하이3 (24)
국어 : 80
영어 : 90
수학 : 70
총점 : 240
평균 : 80.0
성적표 --------------------
이름: 하이4 (25)
국어 : 80
영어 : 90
수학 : 70
총점 : 240
평균 : 80.0
성적표 --------------------
이름: 하이5 (26)
국어 : 80
영어 : 90
수학 : 70
총점 : 240
평균 : 80.0


#### 클래스 상속과 오버라이딩

In [15]:
class MoreFourCal(FourCal):
    pass

mcal_1 = MoreFourCal(100, 8)
print(mcal_1.add(), mcal_1.sub(), mcal_1.mul(), mcal_1.div())

108 92 800 12.5


In [16]:
class MoreFourCal(FourCal):
    # 새로운 함수 추가
    def pow(self):
        return self.first**self.second
    
    # 메서드 오버라이딩 : 기존의 함수 기능 수정
    def div(self):
        if self.second == 0:
            return 0
        else:
            return self.first / self.second

In [17]:
mcal_2 = MoreFourCal(4, 0)
print(mcal_2.pow(), mcal_2.div())

1 0


### 2. 모듈과 패키지

#### 모듈

##### 모듈 생성

In [18]:
# mod1.py 파일
print("mod1.py 시작")

PI = 3.14

def add(n1, n2):
    return n1 + n2

def sub(n1, n2):
    return n1 - n2

print('mod1.py 끝')

mod1.py 시작
mod1.py 끝


##### 모듈 불러오기

In [ ]:
# app.py 파일
import mod1

print(mod1.PI)
print(mod1.add(10, 20))
print(mod1.sub(10, 3))

# 출력 결과:
# mod1.py 시작
# mod1.py 끝
# 3.14
# 30
# 7

##### 모듈 이름 없이 함수 이름만으로 불러오기

In [ ]:
from mod1 import PI, add, sub

print(PI)
print(add(100, 20))
print(sub(10, 3))

# 출력 결과:
# mod1.py 시작
# mod1.py 끝
# 3.14
# 120
# 7

##### 모듈 내 모든 함수 불러오기

In [ ]:
from mod1 import *

print(PI)
print(add(100, 20))
print(sub(10, 3))

# 출력 결과:
# mod1.py 시작
# mod1.py 끝
# 3.14
# 120
# 7

##### 모듈 별칭 만들기

In [ ]:
import mod1 as mo

### 3. 표준 라이브러리

- 따로 설치하지 않아도 파이썬에서 기본 제공

#### datetime

In [20]:
import datetime

day1 = datetime.date(2025, 6, 12)
day2 = datetime.date(2025, 1, 1)

print(day1)
print(day1 - day2)

2025-06-12
162 days, 0:00:00


#### time

In [21]:
import time

print(time.time())
print(time.localtime())
print(f"{time.localtime().tm_year}년 {time.localtime().tm_mon}월 {time.localtime().tm_mday}일")
print(time.ctime())

1749717177.1589074
time.struct_time(tm_year=2025, tm_mon=6, tm_mday=12, tm_hour=17, tm_min=32, tm_sec=57, tm_wday=3, tm_yday=163, tm_isdst=0)
2025년 6월 12일
Thu Jun 12 17:32:57 2025


#### random

In [22]:
import random

# 0 ~ 1 사이의 실수값(1은 X)을 랜덤으로 
print(random.random())

# 0 ~ 10 사이의 정수값을 랜덤으로
print(random.randint(0, 10))

list_score = []
for s in range(0, 10):
    list_score.append(random.randint(60, 100))

print(list_score)

# 주어진 시퀀스의 요소들 중 하나를 랜덤으로 뽑아줌
print(random.choice([1, 2, 3, 4, 5]))

# 주어진 시퀀스의 요소들 중 k개를 랜덤으로 뽑아줌
print(random.sample([1, 2, 3, 4, 5, 6, 7, 8, 9], 3))

0.35211829932086014
2
[83, 68, 69, 94, 81, 79, 84, 64, 76, 70]
1
[4, 6, 5]


#### os
- 특정 디렉토리의 내용을 모니터링할 때 사용

In [28]:
import os

print(os.environ)

# 현재 디렉토리 이동
os.chdir('c:\\windows')

# 현재 디렉토리 출력
# print(os.getcwd())

os.chdir('C:\\Users\\ez\\Desktop\\sk-shielders-rookies-26\\project\\python')
print(os.getcwd())

# 디렉토리 생성
os.mkdir('test')

# 디렉토리 삭제
os.rmdir('test')

environ({'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\ez\\AppData\\Roaming', 'CHROME_CRASHPAD_PIPE_NAME': '\\\\.\\pipe\\crashpad_10876_ESWAIMOANJSJWYJZ', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'DESKTOP-3M6FEIA', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'EFC_6900': '1', 'ELECTRON_RUN_AS_NODE': '1', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\ez', 'JPY_INTERRUPT_EVENT': '2740', 'LOCALAPPDATA': 'C:\\Users\\ez\\AppData\\Local', 'LOGONSERVER': '\\\\DESKTOP-3M6FEIA', 'NUMBER_OF_PROCESSORS': '12', 'ONEDRIVE': 'C:\\Users\\ez\\OneDrive', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined', 'OS': 'Windows_NT', 'PATH': 'c:\\Users\\ez\\Desktop\\sk-shielders-rookies-26\\project\\python\\.venv\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\

#### json

In [24]:
import json

with open('data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
    print(f"{data} -> {type(data)}")

json_str_data = json.dumps(data)
print(f"{json_str_data} -> {type(json_str_data)}")

{'name': '하이', 'age': 30, 'number': 7} -> <class 'dict'>
{"name": "\ud558\uc774", "age": 30, "number": 7} -> <class 'str'>


### 4. 외부 라이브러리

#### Numpy

- pip install numpy 로 설치하기

In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

print(arr + 10)

[1 2 3 4 5] <class 'numpy.ndarray'>
[11 12 13 14 15]


##### 배열 생성


In [26]:
# 0으로 채워지는 배열 생성
zeros = np.zeros((3, 3))
print(zeros)

# 1로 채우는 배열 생성
ones = np.ones((3, 2))
print(ones)

# 일련번호 생성되는 배열 생성
# 0 ~ 10 사이의 숫자를 2씩 간격으로
seq_1 = np.arange(0, 10, 2)
print(seq_1)

# 지정된 범위 안에서 동일한 간격으로 숫자를 생성
# 0 ~ 1사이의 5개로 구분
linspace = np.linspace(0, 1, 5)
print(linspace)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


##### 배열의 속성 확인

In [27]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(arr1))

# 배열의 크기 (행, 열)
print(arr1.shape)

# 배열의 차원
print(arr1.ndim)

# 배열 요소의 개수
print(arr1.size)

# 데이터의 타입
print(arr1.dtype)

<class 'numpy.ndarray'>
(3, 3)
2
9
int64
